mqtt:
  enabled: false

go2rtc:
  streams:
    rplcam7_stream:
      - rtsp://rplcam7.cels.anl.gov:554/s2
    rplcam7:
      - ffmpeg:rplcam7_stream#video=h264#rotate=0
    # rplcam8_stream:
    #   - rtsp://rplcam8.cels.anl.gov:554/s2
    # rplcam8:
    #   - ffmpeg:rplcam8_stream#video=h264#rotate=0
    rplcam9_stream:
      - rtsp://rplcam9.cels.anl.gov:554/s2
    rplcam9:
      - ffmpeg:rplcam9_stream#video=h264#rotate=0
    rplcam10_stream:
      - rtsp://rplcam10.cels.anl.gov:554/s2
    rplcam10:
      - ffmpeg:rplcam10_stream#video=h264#rotate=0
    rplcam11_stream:
      - rtsp://rplcam11.cels.anl.gov:554/s2
    rplcam11:
      - ffmpeg:rplcam11_stream#video=h264#rotate=0

birdseye:
  enabled: true
  mode: continuous

cameras:
  rplcam7:
    ffmpeg:
      # hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://localhost:8554/rplcam7
          roles:
            - detect
  # rplcam8:
  #   ffmpeg:
  #     # hwaccel_args: preset-nvidia-h264
  #     inputs:
  #       - path: rtsp://localhost:8554/rplcam8
  #         roles:
  #           - detect
  rplcam9:
    ffmpeg:
      # hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://localhost:8554/rplcam9
          roles:
            - detect
  rplcam10:
    ffmpeg:
      # hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://localhost:8554/rplcam10
          roles:
            - detect
  rplcam11:
    ffmpeg:
      # hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://localhost:8554/rplcam11
          roles:
            - detect
version: 0.14
camera_groups:
  Birdseye:
    order: 1
    icon: LuActivity
    cameras: birdseye
