name: rpl_sdl
services:
  # * Databases and infra
  rpl_mongodb:
    container_name: rpl_mongodb
    image: mongo:8.0
    ports:
      - 27017:27017
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-./}.madsci/mongodb:/data/db
  rpl_redis:
    container_name: rpl_redis
    image: redis:7.4
    ports:
      - 6379:6379
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-./}.madsci/redis:/data
  rpl_postgres:
    container_name: rpl_postgres
    image: postgres:17
    environment:
      - POSTGRES_USER=rpl
      - POSTGRES_PASSWORD=rpl
      - POSTGRES_DB=resources
    ports:
      - 5432:5432
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-./}.madsci/postgres:/var/lib/postgresql/data
  # * MADSci Managers
  rpl_event_manager:
    container_name: rpl_event_manager
    image: ghcr.io/ad-sdl/madsci:latest
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
    network_mode: host
    volumes:
      - ./managers:/home/madsci/managers
      - ${LOCAL_WORKSPACE_FOLDER:-./}.madsci:/home/madsci/.madsci/
    command: python -m madsci.event_manager.event_server --definition managers/rpl_sdl_event_manager.manager.yaml
    depends_on:
      - rpl_mongodb
  autobots_wc_manager:
    container_name: autobots_wc_manager
    image: ghcr.io/ad-sdl/madsci:latest
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
    network_mode: host
    volumes:
      - ./workcells:/home/madsci/workcells
      - ${LOCAL_WORKSPACE_FOLDER:-./}.madsci:/home/madsci/.madsci/
    command: python -m madsci.workcell_manager.workcell_server --definition workcells/autobots_wc.workcell.yaml
    restart: on-failure
    depends_on:
      - rpl_redis
      - rpl_event_manager
      - rpl_data_manager
  lab_manager:
    container_name: lab_manager
    image: ghcr.io/ad-sdl/madsci_dashboard:latest
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
    network_mode: host
    volumes:
      - ./managers:/home/madsci/managers
      - ${LOCAL_WORKSPACE_FOLDER:-./}../MADSci/src/madsci_squid/ui:/home/madsci/ui
      - ${LOCAL_WORKSPACE_FOLDER:-./}.madsci:/home/madsci/.madsci/
    command: python -m madsci.squid.lab_server --definition managers/rpl_sdl_lab_manager.manager.yaml
    restart: on-failure
    depends_on:
      - rpl_redis
      - rpl_event_manager
      - rpl_data_manager
  rpl_resource_manager:
    container_name: rpl_resource_manager
    image: ghcr.io/ad-sdl/madsci:latest
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
    network_mode: host
    volumes:
      - ./managers:/home/madsci/managers
      - ${LOCAL_WORKSPACE_FOLDER:-./}.madsci:/home/madsci/.madsci/
    command: python -m madsci.resource_manager.resource_server --definition managers/rpl_sdl_resource_manager.manager.yaml
    depends_on:
      - rpl_postgres
      - rpl_event_manager
  rpl_experiment_manager:
    container_name: rpl_experiment_manager
    image: ghcr.io/ad-sdl/madsci:latest
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
    network_mode: host
    restart: on-failure
    volumes:
      - ./managers:/home/madsci/managers
      - ${LOCAL_WORKSPACE_FOLDER:-./}.madsci:/home/madsci/.madsci/
    command: python -m madsci.experiment_manager.experiment_server --definition managers/rpl_sdl_experiment_manager.manager.yaml
    depends_on:
      - rpl_mongodb
      - rpl_event_manager
  rpl_data_manager:
    container_name: rpl_data_manager
    image: ghcr.io/ad-sdl/madsci:latest
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
    network_mode: host
    volumes:
      - ./managers:/home/madsci/managers
      - ${LOCAL_WORKSPACE_FOLDER:-./}.madsci:/home/madsci/.madsci/
    command: python -m madsci.data_manager.data_server --definition managers/rpl_data_manager.manager.yaml
    depends_on:
      - rpl_mongodb
      - rpl_event_manager
  # * Nodes
  camera_1:
    container_name: camera1
    image: ghcr.io/ad-sdl/camera_module:latest
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
    network_mode: host
    devices:
      - /dev/video0:/dev/video0
    volumes:
      - ./nodes:/home/madsci/nodes
    command: python -m camera_rest_node --definition nodes/camera_1.node.yaml
  sciclops_node:
    image: ghcr.io/ad-sdl/sciclops_module:latest
    container_name: sciclops_node
    environment:
      - USER_ID=0
      - GROUP_ID=0
    # Will not connect to usb unless user is root :(
    volumes:
      - ./nodes:/home/madsci/nodes
      - /dev:/dev
    command: python -m sciclops_rest_node --definition nodes/sciclops.node.yaml
    network_mode: host
    privileged: true
    restart: unless-stopped
  pf400_node:
    image: ghcr.io/ad-sdl/pf400_module:latest
    container_name: pf400_node
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
    network_mode: host
    volumes:
      - ./nodes:/home/madsci/nodes
    command: python -m pf400_rest_node --definition nodes/pf400.node.yaml
    restart: unless-stopped
  ot2_gamma:
    container_name: ot2_gamma
    image: ghcr.io/ad-sdl/ot2_module:latest
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
    network_mode: host
    volumes:
      - ./nodes:/home/madsci/nodes
    command: python -m ot2_rest_node --definition nodes/ot2_gamma.node.yaml
