name: rpl_sdl
services:
  # * Databases and infra
  rpl_mongodb:
    container_name: rpl_mongodb
    image: mongodb/mongodb:8.0
    ports:
      - 27017:27017
  rpl_redis:
    container_name: rpl_redis
    image: redis:7.4
    ports:
      - 6379:6379
  rpl_postgres:
    container_name: rpl_postgres
    image: postgres:17
    environment:
      - POSTGRES_USER=rpl
      - POSTGRES_PASSWORD=rpl
      - POSTGRES_DB=resources
    ports:
      - 5432:5432
  # * MADSci Managers
  rpl_event_manager:
    container_name: rpl_event_manager
    image: madsci:0.1.0
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
    network_mode: host
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-./}:/home/madsci/rpl/
      - ${LOCAL_WORKSPACE_FOLDER:-./}.madsci:/home/madsci/.madsci/
    command: python -m madsci.event_manager.event_server --definition /home/madsci/rpl/managers/rpl_sdl_event_manager.manager.yaml
    depends_on:
      - rpl_mongodb
  autobots_wc_manager:
    container_name: autobots_wc_manager
    image: madsci:0.1.0
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
    network_mode: host
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-./}:/home/madsci/rpl/
      - ${LOCAL_WORKSPACE_FOLDER:-./}.madsci:/home/madsci/.madsci/
    command: python -m madsci.workcell_manager.workcell_server --definition /home/madsci/rpl/workcells/autobots_wc.workcell.yaml
    depends_on:
      - rpl_redis
  rpl_resource_manager:
    container_name: rpl_resource_manager
    image: madsci:0.1.0
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
    network_mode: host
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-./}:/home/madsci/rpl/
      - ${LOCAL_WORKSPACE_FOLDER:-./}.madsci:/home/madsci/.madsci/
    command: python -m madsci.resource_manager.resource_server --definition /home/madsci/rpl/managers/rpl_sdl_resource_manager.manager.yaml
    depends_on:
      - rpl_postgres
  rpl_experiment_manager:
    container_name: rpl_experiment_manager
    image: madsci:0.1.0
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
    network_mode: host
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-./}:/home/madsci/rpl/
      - ${LOCAL_WORKSPACE_FOLDER:-./}.madsci:/home/madsci/.madsci/
    command: python -m madsci.experiment_manager.experiment_server --definition /home/madsci/rpl/managers/rpl_sdl_experiment_manager.manager.yaml
    depends_on:
      - rpl_mongodb
